services:
  visascraper:
    build: .
    container_name: visa-parser
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - parser-data:/app/src/visascraper/data
      - ./logs:/app/logs
      # При необходимости пробросьте локальный JSON сервисного аккаунта:
      # - ./src/service_account.json:/app/src/service_account.json:ro

volumes:
  parser-data:
